// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = {
  "tag": null,
  "branch": "copilot/update-icons-to-loading-svg",
  "commit": "47dc361",
  "isDirty": true,
  "buildTime": "2025-10-26T10:49:55.332Z",
  "version": "copilot/update-icons-to-loading-svg-47dc361-dirty",
  "shortVersion": "47dc361"
};

export const getVersionString = () => {
  return VERSION_INFO.version;
};

export const getShortVersionString = () => {
  return VERSION_INFO.shortVersion;
};
