// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = {
  "tag": "1.0.0",
  "branch": "SThor/issue42",
  "commit": "64aefc7",
  "isDirty": true,
  "buildTime": "2025-07-22T20:24:01.728Z",
  "version": "1.0.0",
  "shortVersion": "1.0.0"
};

export const getVersionString = () => {
  return VERSION_INFO.version;
};

export const getShortVersionString = () => {
  return VERSION_INFO.shortVersion;
};
