// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = {
  "tag": null,
  "branch": "feature/22-fix-ynab-connection-again",
  "commit": "b0ff3d8",
  "isDirty": true,
  "buildTime": "2025-07-03T18:50:24.827Z",
  "version": "feature/22-fix-ynab-connection-again-b0ff3d8-dirty",
  "shortVersion": "b0ff3d8"
};

export const getVersionString = () => {
  return VERSION_INFO.version;
};

export const getShortVersionString = () => {
  return VERSION_INFO.shortVersion;
};
